name: Linters

on: [push]

jobs:
  linters:
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Cache Poetry
        id: poetry-cache
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry
      - name: Setup poetry
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: pyright
        uses: jakebailey/pyright-action@v1

  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - run: pip install flake8
      - name: flake8
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: flake8
          run: flake8 main.py

  black:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: black
        uses: psf/black@stable
