name: Tests

on: [push]

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      POETRY_VIRTUALENVS_CREATE: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-pip
          restore-keys: ${{runner.os}}-pip
      - name: Setup poetry
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: Run main script
        run: poetry run python main.py
